config/routes.rb
HomeBinder::Application.routes.draw do
   
  
  mount StripeEvent::Engine => '/subscriptions/webhook', :as => 'stripe_webhook'
  
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :config,                  :only => [:index]
      resources :registrations,           :only => [:create, :show]
      resources :user_tokens,             :only => [:create, :destroy]
      resources :users,                   :only => [:show]
      resources :user_profiles,           :only => [:index, :update]
      resources :passwords,               :only => [:create, :update]
      resources :binders do
        resources :notes
        resources :shares,                :only => [:index, :create]

      end
      resources :property_types,          :only => [:index]
      resources :structures do
        resources :notes
      end
      resources :construction_styles,     :only => [:index]
      resources :construction_types,      :only => [:index]
      resources :heat_types,              :only => [:index]
      resources :heat_sources,            :only => [:index]
      resources :areas do
        resources :notes
      end
      resources :area_types,              :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :paints do
        resources :notes
      end
      resources :paint_manufacturers,     :only => [:index]
      resources :paint_types,             :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :maintenance_items do
        resources :notes
      end
      resources :maintenance_cycles,      :only => [:index]
      resources :maintenance_events
      resources :projects do
        resources :notes
      end
      resources :project_types,           :only => [:index]
      resources :project_statuses,        :only => [:index]
      resources :binder_contractors do
        resources :notes
      end
      resources :contractor_types,        :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :appliance_manufacturers, :only => [:index]
      resources :appliance_models,        :only => [:index]
      resources :inventory_items do
        resources :notes
      end
      resources :inventory_item_types,    :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :finish_makes,            :only => [:index]
      resources :finish_models,           :only => [:index]
      resources :receipts do
        resources :notes
      end
      resources :stores,                  :only => [:index]
      resources :contractors,             :only => [:show]
      resources :shares,                  :only => [:index, :update, :destroy]
      resources :subscriptions
      resources :plans,                   :only => [:show]
      resources :coupons,                 :only => [:show]
      resources :documents
      resources :images
      resources :reports,                 :only => [:index]
      resources :tags,                    :only => [:create, :destroy]
      resources :user_roles,              :only => [:create]
      resources :partners
      resources :logos,                   :only => [:index, :create, :destroy]   
      resources :seller_reports,          :only => [:create, :show, :update] 
      resources :seller_report_pdfs,      :only => [:show]
      resources :recalls,                 :only => [:index]
      resources :transfers,               :only => [:create]
      resources :free_trials,             :only => [:create]
    end
  end

  namespace :admin do
    resources :users,                :only => [:index, :destroy]
    resources :partners
    resources :logos
    resources :seller_reports,       :only => [:index]
    resources :user_roles,           :only => [:create]
  end
  
  resources :api_keys

  root :to => "home#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :notable, :polymorphic => true
  
  def get_notable
    self.notable_type.classify.constantize.find(self.notable_id)
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < Api::V1::ApiController
  
  before_filter :load_notable, :only => [:index, :create]
  
  def index
    @notes = @notable.notes
  end
  
  def show
    @note = Note.find(params[:id])
  end

  def create
    @note = @notable.notes.new(params[:note])
    
    if not @note.save
      render status :unprocessable_entity, json: @note.errors
    end
    
  end

  def update
    @note = Note.find(params[:id])

    if not @note.update_attributes(params[:note])
      render status: :unprocessable_entity, json: @note.errors  
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    head :no_content
  end
  
 private
 
 def load_notable
    resource, id = request.path.split('/')[3,4]
    @notable = resource.singularize.classify.constantize.find(id)
  end

  def find_notable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_filter :load_notable
  
  # GET /notes
  # GET /notes.json
  def index
    @notes = @notable.notes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
      format.js
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = @notable.notes.new(created_by: working_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
      format.js
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @notable.notes.new(params[:note])
    
    respond_to do |format|
      if @note.save
        @notes = @notable.notes
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @deletedId = @note.id
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
      format.js
    end
  end
  
 private
 
 def load_notable
    resource, id = request.path.split('/')[1, 2]
    @notable = resource.singularize.classify.constantize.find(id)
  end

  def find_notable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_container.html.erb
<div id="item_<%= itemid %>_notes">
	<div id="item_<%= itemid %>_notes_content" class="item_notes_content"></div>
</div>
<br/>

app/views/notes/_form.html.erb
<%= simple_form_for([@notable, @note], :html => { :class => "data_form" }, :remote => true) do |f| %>
  
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  	<h3><%= t(:note) %></h3>
  </div>
  
  <div class="form-inputs modal-body">
  	<%= f.error_notification %>
  	<%= f.hidden_field :notable_id %>
  	<%= f.hidden_field :created_by %>
  	<%= f.input :content, :as => :text, :autofocus => true, :input_html => { :rows => '5', :class => 'span12', :maxlength => 250 } %>
  </div>

  <div class="modal-footer">
  	<%= f.button :submit, t(:save), :class => "btn btn-hb" %>
  	<button type="button" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:cancel) %></button>
  </div>
<% end %>

app/views/notes/_notes.html.erb
<% @notes.each do |note| %> 
	<div id="note_<%= note.id %>" class="note">
		<div class="pull-left">
			<%= note.content %>
			<div class="created_at">
				<%= note.created_at.strftime("%m/%d/%Y") %>
			</div>
		</div>
		<div class="pull-right">
			<%= link_to note, :confirm => t(:confirm_delete), :method => :delete, :remote => true, :class => 'delete_post', 'data-toggle' => "tooltip", 'title' => t(:delete_tip) do %>
	     		<i class='icon-remove'></i>
	     	<% end %>
		</div>
		<div class="clear-float"></div>
	</div>
<% end %>

app/views/notes/create.js.erb
closeModalForm();
updateTabContent(<%= @notable.id %>, "<%= escape_javascript(render(:partial => "notes")) %>", "notes")

app/views/notes/destroy.js.erb
$("#note_<%= @deletedId %>").remove();

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/index.js.erb
showTabContent(<%= @notable.id %>, "<%= escape_javascript(render(:partial => "notes")) %>", "notes");

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/new.js.erb
showModalForm("<%= escape_javascript(render(:partial => "form")) %>");

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>