config/routes.rb
HomeBinder::Application.routes.draw do
   
  
  mount StripeEvent::Engine => '/subscriptions/webhook', :as => 'stripe_webhook'
  
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :config,                  :only => [:index]
      resources :registrations,           :only => [:create, :show]
      resources :user_tokens,             :only => [:create, :destroy]
      resources :users,                   :only => [:show]
      resources :user_profiles,           :only => [:index, :update]
      resources :passwords,               :only => [:create, :update]
      resources :binders do
        resources :notes
        resources :shares,                :only => [:index, :create]

      end
      resources :property_types,          :only => [:index]
      resources :structures do
        resources :notes
      end
      resources :construction_styles,     :only => [:index]
      resources :construction_types,      :only => [:index]
      resources :heat_types,              :only => [:index]
      resources :heat_sources,            :only => [:index]
      resources :areas do
        resources :notes
      end
      resources :area_types,              :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :paints do
        resources :notes
      end
      resources :paint_manufacturers,     :only => [:index]
      resources :paint_types,             :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :maintenance_items do
        resources :notes
      end
      resources :maintenance_cycles,      :only => [:index]
      resources :maintenance_events
      resources :projects do
        resources :notes
      end
      resources :project_types,           :only => [:index]
      resources :project_statuses,        :only => [:index]
      resources :binder_contractors do
        resources :notes
      end
      resources :contractor_types,        :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :appliance_manufacturers, :only => [:index]
      resources :appliance_models,        :only => [:index]
      resources :inventory_items do
        resources :notes
      end
      resources :inventory_item_types,    :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :finish_makes,            :only => [:index]
      resources :finish_models,           :only => [:index]
      resources :receipts do
        resources :notes
      end
      resources :stores,                  :only => [:index]
      resources :contractors,             :only => [:show]
      resources :shares,                  :only => [:index, :update, :destroy]
      resources :subscriptions
      resources :plans,                   :only => [:show]
      resources :coupons,                 :only => [:show]
      resources :documents
      resources :images
      resources :reports,                 :only => [:index]
      resources :tags,                    :only => [:create, :destroy]
      resources :user_roles,              :only => [:create]
      resources :partners
      resources :logos,                   :only => [:index, :create, :destroy]   
      resources :seller_reports,          :only => [:create, :show, :update] 
      resources :seller_report_pdfs,      :only => [:show]
      resources :recalls,                 :only => [:index]
      resources :transfers,               :only => [:create]
      resources :free_trials,             :only => [:create]
    end
  end

  namespace :admin do
    resources :users,                :only => [:index, :destroy]
    resources :partners
    resources :logos
    resources :seller_reports,       :only => [:index]
    resources :user_roles,           :only => [:create]
  end
  
  resources :api_keys

  root :to => "home#index"

end

app/models/recall.rb
require 'httparty'

class Recall < ActiveResource::Base
  include HTTParty
  base_uri 'api.usa.gov'
  default_params :output => 'json'
  format :json
  
  def self.find_by_manufacturer_model(manufacturer, model = nil, start_date = nil, page = 1)
    query = ''
    if not manufacturer.nil? and not manufacturer.empty?
      query = manufacturer
    end
    
    if not model.nil? and not model.empty?
      query = query.empty? ? model : query << '+' << model
    end
    
    if start_date.nil?
      get('/recalls/search', :query => {:organization => 'CPSC', :page => page, :query => query})
    else
      get('/recalls/search', :query => {:organization => 'CPSC', :start_date => start_date, :page => page, :query => query})
    end
  end
  
  def self.find_by_upc(upc, start_date = nil, page = 1)
    if start_date.nil?
      get('/recalls/search', :query => {:organization => 'CPSC', :upc => upc, :page => page})
    else
      get('/recalls/search', :query => {:organization => 'CPSC', :upc => upc, :start_date => start_date, :page => page})
    end
  end
  
end
  

app/controllers/api/v1/recalls_controller.rb
class Api::V1::RecallsController < Api::V1::ApiController
  
  def index
    @appliance = Appliance.find(params[:appliance_id])
    @page = params[:page].nil? ? 0 : params[:page]
    
    binder = Binder.includes(:subscription).find(@appliance.binder_id)
    if binder.subscription.plan_id == 'free'
      raise 'Permission Denied'
    end
    
    @page = params[:page].nil? ? 1 : params[:page].to_i
    @recallCheck = RecallCheck.new(@appliance)
    @recallCheck.run(nil, @page)
  end
  
end

app/controllers/recalls_controller.rb
class RecallsController < ApplicationController
  
  def index
    @appliance = Appliance.find(params[:appliance_id])
    
    binder = Binder.includes(:subscription).find(@appliance.binder_id)
    if binder.subscription.plan_id == 'free'
      raise 'Permission Denied'
    end
    
    @page = params[:page].nil? ? 1 : params[:page].to_i
    @recallCheck = RecallCheck.new(@appliance)
    @recallCheck.run(nil, @page)
  end
  
end

app/helpers/recalls_helper.rb
module RecallsHelper
end

app/views/recalls/index.html.erb
<div class="offset3 span6">
	<div class="row">
		<div class="span12">
			<h3>Recalls for <%= @appliance.name %></h3>
			<h4><%= @appliance.manufacturer unless @appliance.manufacturer.nil? %>&nbsp;
				<%= @appliance.model unless @appliance.model.nil? %>&nbsp;
				<%= "(UPC: #{@appliance.upc})" unless @appliance.upc.nil? or @appliance.upc.empty? %></h4>
		</div>	
	</div>
	<div class="row">
		<% if @recallCheck.total == 0 %>
			<div class="object-block">
				<h3>No recalls</h3>
			</div>
		<% else %>
			<% @recallCheck.recalls.each do |r| %>
				<div class="span12 object-block recall-block">
					<table class='recall-table'>
						<tr>
							<th>Recall Number:</th>
							<td><%= r["recall_number"] %></td>
						</tr>
						<tr>
							<th>Recall Date:</th>
							<td><%= r["recall_date"] %></td>
						</tr>
						<tr>
							<th>Manufacturers:</th>
							<td colspan="3">
								<% if not r["manufacturers"].nil? %>
									<% r["manufacturers"].each do |m| %>
										<%= m %><br />
									<% end %>
								<% end %>
							</td>
						</tr>
						<tr>
							<th>Product Types:</th>
							<td colspan="3">
								<% if not r["product_types"].nil? %>
									<% r["product_types"].each do |pt| %>
										<%= pt %><br />
									<% end %>
								<% end %>
							</td>
						</tr>
						<tr>
							<th>Descrptions:</th>
							<td colspan="3">
								<% if not r["descriptions"].nil? %>
									<% r["descriptions"].each do |d| %>
										<%= d %><br />
									<% end %>
								<% end %>
							</td>
						</tr>
						<tr>
							<th>UPC Codes:</th>
							<td colspan="3">
								<% if not r["upcs"].nil? %>
									<% r["upcs"].each do |u| %>
										<%= u %><br />
									<% end %>
								<% end %>
							</td>
						</tr>
						<tr>
							<th>Hazards:</th>
							<td colspan="3">
								<% if not r["hazards"].nil? %>
									<% r["hazards"].each do |h| %>
										<%= h %><br />
									<% end %>	
								<% end %>
							</td>
						</tr>
						<tr class="tr-last">
							<th></th>
							<td><a href="<%= r["recall_url"] %>" target="_blank">More Information</a></td>
						</tr>
					</table>
				</div>
			<% end %>
		<% end %>
	</div>
	<div class="row">
		<div class="back-to-appliances">
			<%= link_to "Back to appliances", binder_appliances_path(@appliance.binder_id) %>	
			<% if @page < @recallCheck.pages %>
				<%= link_to "Next", appliance_recalls_path(@appliance, :page => (@page+1).to_s), :class => 'pull-right'%>
			<% end %>
		</div>	
	</div>
</div>