config/routes.rb
HomeBinder::Application.routes.draw do
   
  
  mount StripeEvent::Engine => '/subscriptions/webhook', :as => 'stripe_webhook'
  
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :config,                  :only => [:index]
      resources :registrations,           :only => [:create, :show]
      resources :user_tokens,             :only => [:create, :destroy]
      resources :users,                   :only => [:show]
      resources :user_profiles,           :only => [:index, :update]
      resources :passwords,               :only => [:create, :update]
      resources :binders do
        resources :notes
        resources :shares,                :only => [:index, :create]

      end
      resources :property_types,          :only => [:index]
      resources :structures do
        resources :notes
      end
      resources :construction_styles,     :only => [:index]
      resources :construction_types,      :only => [:index]
      resources :heat_types,              :only => [:index]
      resources :heat_sources,            :only => [:index]
      resources :areas do
        resources :notes
      end
      resources :area_types,              :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :paints do
        resources :notes
      end
      resources :paint_manufacturers,     :only => [:index]
      resources :paint_types,             :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :maintenance_items do
        resources :notes
      end
      resources :maintenance_cycles,      :only => [:index]
      resources :maintenance_events
      resources :projects do
        resources :notes
      end
      resources :project_types,           :only => [:index]
      resources :project_statuses,        :only => [:index]
      resources :binder_contractors do
        resources :notes
      end
      resources :contractor_types,        :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :appliance_manufacturers, :only => [:index]
      resources :appliance_models,        :only => [:index]
      resources :inventory_items do
        resources :notes
      end
      resources :inventory_item_types,    :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :finish_makes,            :only => [:index]
      resources :finish_models,           :only => [:index]
      resources :receipts do
        resources :notes
      end
      resources :stores,                  :only => [:index]
      resources :contractors,             :only => [:show]
      resources :shares,                  :only => [:index, :update, :destroy]
      resources :subscriptions
      resources :plans,                   :only => [:show]
      resources :coupons,                 :only => [:show]
      resources :documents
      resources :images
      resources :reports,                 :only => [:index]
      resources :tags,                    :only => [:create, :destroy]
      resources :user_roles,              :only => [:create]
      resources :partners
      resources :logos,                   :only => [:index, :create, :destroy]   
      resources :seller_reports,          :only => [:create, :show, :update] 
      resources :seller_report_pdfs,      :only => [:show]
      resources :recalls,                 :only => [:index]
      resources :transfers,               :only => [:create]
      resources :free_trials,             :only => [:create]
    end
  end

  namespace :admin do
    resources :users,                :only => [:index, :destroy]
    resources :partners
    resources :logos
    resources :seller_reports,       :only => [:index]
    resources :user_roles,           :only => [:create]
  end
  
  resources :api_keys

  root :to => "home#index"

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many    :contractor_abilities
  has_many    :binder_contractors
  has_many    :binders, :through => :binder_contractors
  has_one     :address, :as => :addressable
  
  
  accepts_nested_attributes_for :address
  
  before_save { |c| c.name = c.name.downcase }
  
  phony_normalize :phone, :default_country_code => 'US'
  
  validates_presence_of     :name, :message => I18n.t(:value_required)
  validates_length_of       :name, :maximum => 100
  #validates_format_of       :phone,  :with => /\d{3}-\d{3}-\d{4}/, :message => "bad format, use xxx-xxx-xxxx", :allow_blank => true
  validates_plausible_phone :phone, :presence => false, :message => 'Invalid phone number'
  #validates_format_of       :email, :with => /^[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/, :allow_blank => true
  validates_length_of       :url, :maximum => 250
  validates_length_of       :details, :maximum => 500
  
  #scope :my_contractors, ->(binder_id, user_id) { Binder.joins(:contractors).merge(:verified_or_created_by).select('contractors.*').where(binders: { id: binder_id })}
  scope :verified_or_created_by, ->(user_id) { Contractor.where("contractors.verified = ? or contractors.created_by = ?", true, user_id).order("name") }
  
  after_create :add_new_typeahead_options
  
  def add_new_typeahead_options
    ContractorType.where(:name => self.contractor_type.downcase).first_or_create(:verified => false, :created_by => self.created_by) unless self.contractor_type.nil?
  end
  
end

app/models/contractor_type.rb
class ContractorType < ActiveRecord::Base
  # attr_accessible :title, :body
  before_save { |c| c.name = c.name.downcase }
  
  def self.available(user_id)
    ContractorType.where("verified = ? OR created_by = ?", true, user_id).order("name").map { |con| con.name.titleize }
  end
end

app/controllers/api/v1/contractors_controller.rb
class Api::V1::ContractorsController < Api::V1::ApiController
  def show
    @contractor = Contractor.find(params[:id])
    
    render status: :not_found, json: { :message => "Contractor not found" } unless not @contractor.nil?
  end
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  layout 'binder'
  include UploadersHelper
  
  # GET /contractors
  # GET /contractors.json
  def index
    load_binder
    initialize_uploader(current_user.id, @binder.id, 'contractors')
    
    @contractors = working_binder.contractors
    @count = @contractors.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contractors }
    end
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
    @contractor = Contractor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contractor }
    end
  end

  # GET /contractors/new
  # GET /contractors/new.json
  def new
    @contractor = Contractor.new(created_by: current_user.id, verified: false)
    @contractor.build_address

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contractor }
      format.js
    end
  end

  # GET /contractors/1/edit
  def edit
    @contractor = Contractor.find(params[:id])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(params[:contractor])
    working_binder.contractors << @contractor

    respond_to do |format|
      if working_binder.save
        @contractors = working_binder.contractors
        format.html { redirect_to binder_contractors_path(working_binder), notice: 'Contractor was successfully created.' }
        format.json { render json: @contractor, status: :created, location: @contractor }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /contractors/1
  # PUT /contractors/1.json
  def update
    @contractor = Contractor.find(params[:id])

    respond_to do |format|
      if @contractor.update_attributes(params[:contractor])
        @contractors = working_binder.contractors
        format.html { redirect_to binder_contractors_path(working_binder), notice: 'Contractor was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor = Contractor.find(params[:id])
    working_binder.contractors.delete(@contractor)
    if @contractor.verified == false
      @contractor.destroy
    end
    @contractors = working_binder.contractors

    respond_to do |format|
      format.html { redirect_to binder_contractors_path(working_binder) }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_contractor.html.erb
<table class="table table-condensed">
	<tr>
		<th class="fixed-width"><%= t(:contractor_address)%></th>
	    <td colspan="3">
	    	<% if contractor.address.address1.length > 0 %>
	    		<%= contractor.address.address1 %>,
	    	<% end %> 
	    	<% if contractor.address.address2.length > 0 %>
	    		<%= contractor.address.address2 %>, 
	    	<% end %>
	    	<% if contractor.address.city.length > 0 %>
	    		<%= contractor.address.city %>, 
	    	<% end %>	
	    	<% if contractor.address.state.length > 0 %>
	    		<%= contractor.address.state %>&nbsp;
	    	<% end %>
	    	<% if contractor.address.zip.length > 0 %>
	    		<%= contractor.address.zip %>
	    	<% end %>
	    </td>
	</tr>
	<tr>
		<th class="fixed-width"><%= t(:contractor_phone) %></th>
		<td><%= contractor.phone.phony_formatted(:format => :national, :spaces => '-') unless contractor.phone.nil? %></td>
		<th class="fixed-width"><%= t(:contractor_email) %></th>
		<td><%= contractor.email %></td>
	</tr>
	<tr>
		<th><%= t(:contractor_url) %></th>
		<td><a href="http://<%= contractor.url %>"><%= contractor.url %></a></td>
		<th></th>
		<td></td>
	</tr>
	<tr>
		<th><%= t(:contractor_account_number)%></th>
		<td><%= contractor.account_number %></td>
		<th><%= t(:contractor_contact)%></th>
		<td><%= contractor.contact %></td>
	</tr>
</table>

app/views/contractors/_contractors_simple.html.erb
<% if @contractors.length > 0 %>

	<table class="table">
		<tr>
			<th>Name</th>
			<th>Type</th>
			<th>Phone</th>
		</tr>
		
		<% @contractors[0,3].each do |contractor| %>
		
		<tr>
			<td><%= contractor.name.titleize unless contractor.name.nil? %></td>
			<td><%= contractor.contractor_type %></td>
			<td><%= contractor.phone.phony_formatted(:format => :national, :spaces => '-') unless contractor.phone.nil? %></td>
		</tr>
		
		<% end %>
	
	</table>

<% else %>

	<div class="alert alert-info">You have no contractors, you should add some!</div>

<% end %>

<%= link_to "View All Contractors", binder_binder_contractors_path(working_binder), :class => 'btn btn-hb' %>

app/views/contractors/_form.html.erb
<div class='span6'>
	<%= simple_form_for(@contractor, :html => { :class => "data_form" }, :remote => true) do |f| %>
	  <%= f.error_notification %>
	  <%= f.hidden_field :created_by %>
	
	  <div class="form-inputs">
	  	<%= f.input :name, :autofocus => true, :input_html=> { :class => 'span12' } %>
	  	<%= f.input :contractor_type, :input_html => { :autocomplete => 'off', :class => 'autocomplete', :data => { :name => "con_type", :local => ContractorType.available(current_user.id), :span => "span12" }} %><br /><br />
	  	<%= f.simple_fields_for :address do |a| %>
			<%= render partial: 'addresses/form_for', object: a, as: :f %>
	  	<% end %>
	  	<%= f.input :phone, :input_html => { :class => 'span12'} %>
	  	<%= f.input :email, :input_html => { :class => 'span12'} %>
		<%= f.input :url, :as => :string, :input_html => { :class => 'span12' } %>
		<%= f.input :account_number, :input_html => { :class => 'span12' } %>
		<%= f.input :contact, :input_html => { :class => 'span12' } %>
		<%= f.input :details, :as => :text, :input_html => { :class => 'span12', :rows => '5' } %>
		<%= f.hidden_field :verified %>
	  </div>
	
	  <div class="form-actions">
	    <%= f.button :submit, t(:save), :disable_with => t(:wait), :class => 'btn btn-hb' %>
	    <%= link_to t(:cancel), "#", :class => "btn cancel_data_form cancel_edit_form", 'data-itemid' => @contractor.id, 'data-controller' => 'contractor' %>
	  </div>
	<% end %>
</div>

app/views/contractors/create.js.erb
<% if @contractor.errors.any? %>
	
	prepareDataForm("<%= escape_javascript(render(:partial => "form")) %>");

<% else %>

	closeDataForm();
	updateDataTable(
		"<%= escape_javascript(render(:partial => "shared/resource_index", :locals => { :resources => @contractors })) %>",
		"<%= @contractors.count %>");

<% end %>

app/views/contractors/destroy.js.erb
updateDataTable(
	"<%= escape_javascript(render(:partial => "shared/resource_index", :locals => { :resources => @contractors })) %>",
	"<%= @contractors.count %>");

app/views/contractors/edit.html.erb
<h1>Editing contractor</h1>

<%= render 'form' %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/edit.js.erb
prepareEditForm('contractor', "<%= escape_javascript(render(:partial => "form"))%>");

app/views/contractors/index.html.erb
	<%= content_for :header do %>
		<%= t(:contractor).pluralize %>
	<% end %>
	
	<%= content_for :item_count do %>
		<%= @contractors.count %>
	<% end %>
	
	<%= content_for :toolbarbuttons do %>
		<%= link_to t(:contractor_new), new_binder_contractor_path(working_binder), :id => 'new_item_btn', :class => "btn btn-hb", :remote => true %>
		<%= link_to_function 'Hide All Details', 'hideAllDetails()', :id => 'hideAllButton', :class => 'btn' %>
		<%= link_to_function 'Show All Details', 'showAllDetails()', :id => 'showAllButton', :class => 'btn', :style => 'display:none;' %>
	<% end %>
	
	<%= render :partial => 'shared/resource_index', :locals => { :resources => @contractors } %>
	

app/views/contractors/new.html.erb
<h1>New contractor</h1>

<%= render 'form' %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/new.js.erb
prepareDataForm("<%= escape_javascript(render(:partial => "form"))%>");

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/update.js.erb
<% if @contractor.errors.any? %>
	
	prepareEditForm('contractor', "<%= escape_javascript(render(:partial => "form")) %>");

<% else %>

	updateDataTable(
		"<%= escape_javascript(render(:partial => "shared/resource_index", :locals => { :resources => @contractors })) %>",
		"<%= @contractors.count %>");

<% end %>