config/routes.rb
HomeBinder::Application.routes.draw do
   
  
  mount StripeEvent::Engine => '/subscriptions/webhook', :as => 'stripe_webhook'
  
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :config,                  :only => [:index]
      resources :registrations,           :only => [:create, :show]
      resources :user_tokens,             :only => [:create, :destroy]
      resources :users,                   :only => [:show]
      resources :user_profiles,           :only => [:index, :update]
      resources :passwords,               :only => [:create, :update]
      resources :binders do
        resources :notes
        resources :shares,                :only => [:index, :create]

      end
      resources :property_types,          :only => [:index]
      resources :structures do
        resources :notes
      end
      resources :construction_styles,     :only => [:index]
      resources :construction_types,      :only => [:index]
      resources :heat_types,              :only => [:index]
      resources :heat_sources,            :only => [:index]
      resources :areas do
        resources :notes
      end
      resources :area_types,              :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :paints do
        resources :notes
      end
      resources :paint_manufacturers,     :only => [:index]
      resources :paint_types,             :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :maintenance_items do
        resources :notes
      end
      resources :maintenance_cycles,      :only => [:index]
      resources :maintenance_events
      resources :projects do
        resources :notes
      end
      resources :project_types,           :only => [:index]
      resources :project_statuses,        :only => [:index]
      resources :binder_contractors do
        resources :notes
      end
      resources :contractor_types,        :only => [:index]
      resources :appliances do
        resources :notes
      end
      resources :appliance_manufacturers, :only => [:index]
      resources :appliance_models,        :only => [:index]
      resources :inventory_items do
        resources :notes
      end
      resources :inventory_item_types,    :only => [:index]
      resources :finishes do
        resources :notes
      end
      resources :finish_makes,            :only => [:index]
      resources :finish_models,           :only => [:index]
      resources :receipts do
        resources :notes
      end
      resources :stores,                  :only => [:index]
      resources :contractors,             :only => [:show]
      resources :shares,                  :only => [:index, :update, :destroy]
      resources :subscriptions
      resources :plans,                   :only => [:show]
      resources :coupons,                 :only => [:show]
      resources :documents
      resources :images
      resources :reports,                 :only => [:index]
      resources :tags,                    :only => [:create, :destroy]
      resources :user_roles,              :only => [:create]
      resources :partners
      resources :logos,                   :only => [:index, :create, :destroy]   
      resources :seller_reports,          :only => [:create, :show, :update] 
      resources :seller_report_pdfs,      :only => [:show]
      resources :recalls,                 :only => [:index]
      resources :transfers,               :only => [:create]
      resources :free_trials,             :only => [:create]
    end
  end

  namespace :admin do
    resources :users,                :only => [:index, :destroy]
    resources :partners
    resources :logos
    resources :seller_reports,       :only => [:index]
    resources :user_roles,           :only => [:create]
  end
  
  resources :api_keys

  root :to => "home#index"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  require "stripe"

  belongs_to :binder
  
  #before_save :save_to_stripe
  before_destroy :clean_stripe
  
  #attr_accessor :stripe_token
  #attr_accessor :coupon_id
  #attr_accessor :action
=begin  
  def notify_subscription_canceled(e)
    binder = Binder.find(self.binder_id)
    user = binder.get_owner
    SubscriptionMailer.delay.notify_subscription_canceled(user, binder, e.data)
    # we need to check if the subscription was canceled by stripe due to failed payments
    # if it was then update our database
    cust = Stripe::Customer.retrieve(self.customer_id)
    if not cust.deleted
      cust.delete
      self.plan_id = 'free'
      self.customer_id = nil
      self.payment_status = nil
      self.save
    end
    
  end
  
  def notify_payment_succeeded(e)
    binder = Binder.find(self.binder_id)
    user = binder.get_owner
    SubscriptionMailer.delay.notify_payment_succeeded(user, binder, e.data)
    self.payment_status = "paid"
    self.save
  end
  
  def notify_payment_failed(e)
    binder = Binder.find(self.binder_id)
    user = binder.get_owner
    SubscriptionMailer.delay.notify_payment_failed(user, binder, e.data)
    self.payment_status = 'failed'
    self.save
  end
  
  def cancel
    if not self.customer_id.nil?
      cancel_subscription
      self.save
    end
  end
=end
  
  private
  
  def save_to_stripe
    case self.action
    when 'upgrade'
      subscribe_to_plan
    when 'update'
      update_payment_method
    when 'cancel'
      cancel_subscription
    end
  end
  
  def clean_stripe
    if not self.customer_id.nil?
      cust = Stripe::Customer.retrieve(self.customer_id)
      cust.delete
    end
  end
  
  def cancel_subscription
    return unless not self.customer_id.nil?
    cust = Stripe::Customer.retrieve(self.customer_id)
    if not cust.nil?
      cust.cancel_subscription
      cust.delete
    end
    
    self.plan_id = 'free'
    self.customer_id = nil
    self.payment_status = nil
  end
  
  def subscribe_to_plan
    cust = Stripe::Customer.create(:description =>  "Binder #{self.binder_id}")
    cust.plan = self.plan_id
    cust.card = self.stripe_token unless self.stripe_token.nil? or self.stripe_token.empty?
    cust.coupon = self.coupon_id unless self.coupon_id.nil? || self.coupon_id.empty?
    cust.save
    
    self.customer_id = cust.id
    self.payment_status = 'paid'
  end
  
  def update_payment_method
    customer = Stripe::Customer.retrieve(self.customer_id)
    if not customer.default_card.nil?
      delete_card = customer.cards.retrieve(customer.default_card)
      delete_card.delete
    end
    
    customer.cards.create(:card => self.stripe_token)
    customer.save
    
    # if the user has a failed payment we will try this new card
    if self.payment_status == 'failed'
      Stripe::Invoice.all(:customer => self.customer_id).each do |invoice|
        if invoice.paid == false
          invoice.pay
          break
        end
      end
    end
  end
   
end

app/models/subscription_type.rb
#class SubscriptionType < ActiveRecord::Base
#end

app/controllers/api/v1/subscriptions_controller.rb
class Api::V1::SubscriptionsController < Api::V1::ApiController
  require 'stripe'
  
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscription_wrappers = Array.new
    if params[:user].nil?
      binder = Binder.find(params[:binder_id])
      @subscription_wrappers << SubscriptionWrapper.new(binder)
    else
      binders = @current_user.binders.includes(:subscription).where(:active => true)
      binders.each do |b|
        @subscription_wrappers << SubscriptionWrapper.new(b)
      end
    end
    puts @subscription_wrappers
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])
    @binder = Binder.find(@subscription.binder_id)
    
    @ability.authorize! :subscribe, @binder
    
    @subscription_wrapper = SubscriptionWrapper.new(@binder)
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])
    @binder = Binder.find(@subscription.binder_id)
    @action = params[:subscription_action]
    @card = params[:card].nil? ? nil : params[:card]
    @coupon = params[:coupon].nil? ? nil : params[:coupon]
    
    @ability.authorize! :subscribe, @binder

    begin
        SubscriptionService.update_subscription(@action, @subscription, @card, @coupon)
        @subscription_wrapper = SubscriptionWrapper.new(@binder)
      rescue Stripe::CardError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body[:error]
          
        #render :json => "#{err[:message].titleize}", :status => :unprocessable_entity
        render :json => "Invalid credit card", :status => :unprocessable_entity
      rescue Stripe::InvalidRequestError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body[:error]
          
        render :json => "#{err[:message].titleize}", :status => :unprocessable_entity
      rescue Stripe::AuthenticationError => e
        # Authentication with Stripe's API failed
        # (maybe you changed API keys recently)
        render :json => "We're having trouble processing your request. Try again later.", :status => :unprocessable_entity 
      rescue Stripe::APIConnectionError => e
        # Network communication with Stripe failed
        render :json => "We're having trouble processing your request. Try again later.", status => :unprocessable_entity 
      rescue Stripe::StripeError => e
        # Display a very generic error to the user, and maybe send
        # yourself an email
        render :json => "We're having trouble processing your request. Try again later.", status => :unprocessable_entity
      rescue CardRequiredException => e
        render :json => e.message, :status => :unprocessable_entity
      rescue UnprocessableException => e
        render :json => @subscription.errors, :status => :unprocessable_entity
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    head :no_content
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  require 'stripe'
  layout 'account'
  
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.where(:binder_id => params[:binder_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])
    @binder = Binder.find(@subscription.binder_id)
   
    authorize! :subscribe, Binder.find(@subscription.binder_id)
    
    @standardPlan = Stripe::Plan.retrieve('standard')
    @total = 0.0
    
    if not @subscription.customer_id.nil?
      @customer = Stripe::Customer.retrieve(@subscription.customer_id)
      @card = @customer.default_card.nil? ? nil : @customer.cards.retrieve(@customer.default_card)
      @subtotal = @customer.subscription.plan.amount
      @discount = 0.0
      
      if not @customer.discount.nil?
        @discount = @customer.discount.coupon.amount_off.nil? ?
          @subtotal * (@customer.discount.coupon.percent_off / 100.00) 
          : @customer.discount.coupon.amount_off
      end 
      @total = @subtotal - @discount
    end
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new(binder_id: params[:binder_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to Binder.find(@subscription.binder_id), notice: 'Subscription was successfully created.' }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      begin
        if @subscription.update_attributes(params[:subscription])
          format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
          format.json { render json: @subscription }
        else
          format.html { render action: "edit" }
          format.json { render json: "coupon is bad", status: :unprocessable_entity }
        end
      rescue Stripe::CardError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body[:error]
        
        format.html { render action: "edit" }
        format.json { render json: "#{err[:message].titleize}", status: :unprocessable_entity }
      rescue Stripe::InvalidRequestError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body[:error]
        
        format.html { render action: "edit" }
        format.json { render json: "#{err[:message].titleize}", status: :unprocessable_entity }
      rescue Stripe::AuthenticationError => e
        # Authentication with Stripe's API failed
        # (maybe you changed API keys recently)
        format.html { render action: "edit" }
        format.json { render json: "We're having trouble processing your request. Try again later.", status: :unprocessable_entity }
      rescue Stripe::APIConnectionError => e
        # Network communication with Stripe failed
        format.html { render action: "edit" }
        format.json { render json: "We're having trouble processing your request. Try again later.", status: :unprocessable_entity }
      rescue Stripe::StripeError => e
        # Display a very generic error to the user, and maybe send
        # yourself an email
        format.html { render action: "edit" }
        format.json { render json: "We're having trouble processing your request. Try again later.", status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<div id="freeSubsc" class="pull-left">
	
</div>
<div id="basicSubsc" class="pull-left">
</div>
<%= simple_form_for(@subscription) do |f| %>
						<input id="subscId" type="hidden" />
		  					<div class="payment-errors alert alert-error hide"></div>
		
							<div class="control-group">
							    <label>Card Number</label>
							    <div class="controls">
							    	<input type="text" size="20" data-stripe="number" class="span5"/>
							    </controls>
						  	</div>
		
						  	<div class="control-group">
							    <label>CVC</label>
								<div class="controls">
							    	<input type="text" size="4" data-stripe="cvc" class="span5"/>
							    </div>
							</div>
		
						  	<div class="control-group">
							    <label>Expiration (MM/YYYY)</label>
							    <div class="controls">
							      	<input type="text" maxlength="2" size="2" data-stripe="exp-month" class="span2"/>
							    	<input type="text" maxlength="4" size="4" data-stripe="exp-year" class="span3"/>
								</div>
							</div>
						  
						  	<div class="control-group">
							  	<label>Coupon</label>
							  	<div class="controls">
							  		<input id="coupon_id" type="text" class="span5" />
							  	</div>	
							</div>
						  
						<div class="modal-footer">
						  <button id="submitPayment" type="submit" class="btn btn-success">Submit Payment</button>
						  <button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
						</div>

	<%= f.hidden_field :binder_id %>
	<%= f.hidden_field :stripe_token %>
	<%= f.hidden_field :plan_id %>
	
	<%= f.input :coupon_id, :label => 'Coupon Code' %>
	

	<div class="controls form-actions">
		<%= f.button :submit, t(:ok), :class => "btn btn-hb" %>
		<%= link_to t(:cancel), user_binders_path(working_user), :class => "btn" %>
	</div>
	
<% end %>

app/views/subscriptions/_subscription.html.erb
<div class="modal-header">
	<h3>Subscription</h3>
</div>
<div class="modal-body">
	<table>
		<tr>
			<th>Subscription Level:</th>
			<td id="subscLevelCell"></td>
		</tr>
		<tr>
			<th>Next Renewal On:</th>
			<td id="nextRenewalCell"></td>
		</tr>
		<tr>
			<th>Coupon:</th>
			<td id="couponCell"></td>
		</tr>
	</table>
	
	<div id="beginUpgradeSubscBlock" class="hide">
		<a id="beginUpgradeSubsc" href="#" class="subsc-btn">Upgrade Subscription</a>
	</div>
	<div id="cancelSubscBlock" class="hide">
		<a id="cancelSubsc" href="#" class="subsc-btn">Cancel Subscription</a>
	</div>
	<div id="updateSubscCardBlock" class="hide">
		<a id="updateSubscCard" href="#" class="subsc-btn">Update Payment Method</a>
	</div>
	
	<div id="ccBlock" class="hide">
		<h4>Payment Information</h4>
		<form id="subscriptionForm">
			<input id="subscId" type="hidden" />
			<div class="payment-errors alert alert-error hide"></div>
			
			<div class="control-group">
				<label>Card Number</label>
				<div class="controls">
					<input type="text" size="20" data-stripe="number" class="span5"/>
				</div>
			</div>
			
			<div class="control-group">
				<label>CVC</label>
				<div class="controls">
					<input type="text" size="4" data-stripe="cvc" class="span5"/>
				</div>
			</div>
			
			<div class="control-group">
				<label>Expiration (MM/YYYY)</label>
				<div class="controls">
					<input type="text" maxlength="2" size="2" data-stripe="exp-month" class="span2"/>
					<input type="text" maxlength="4" size="4" data-stripe="exp-year" class="span3"/>
				</div>
			</div>
							  
			<div class="control-group">
				<label>Coupon</label>
				<div class="controls">
					<input id="coupon_id" type="text" class="span5" />
				</div>	
			</div>
							  
		</form>
	</div>
</div>
<div class="modal-footer">
	<button id="submitPaymentButton" class="btn btn-success hide subsc-btn">Submit</button>
	<button id="cancelPaymentButton" type="button" class="btn subsc-btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
</div>

app/views/subscriptions/edit.html.erb
<%= render 'form' %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<div class="page-header">
	<h1>Binder Subscription Level</h1>
	<p>Select a subscription level for this binder below.</p>
</div>

<%= render 'form' %>

app/views/subscriptions/show.html.erb
<div class="offset3 span6">
	<div class="row">
		<div class="span12">
			<div class="pull-left">
			<h3>Subscription for <%= @binder.name %></h3>
			</div>
			<div class="pull-right">
				<p><%= @binder.property.address1 %></p>
	            <p><%= @binder.property.city %>, <%= @binder.property.state %> <%= @binder.property.zip %></p>
			</div>
			<div class="clear-float"></div>
			<div id="notifyUserBlock" class="alert alert-success hide"></div>
			<% if @subscription.payment_status == 'failed'%>
				<div id="paymentFailedNotification" class="alert alert-error">Payment for the binder's subscription failed. Verify your payment information.</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<div class="object-block">
				<table id="subscription-table">
					<tr id="rowSubscription" class="subscription_row">
						<th>Subscription Level:</th>
						<td id="subscLevelCell">
							<%= @subscription.plan_id.titleize %>
							<% if @subscription.plan_id == 'free' %>
								<a id="beginUpgradeSubsc" href="#" class="subsc-btn btn btn-hb">Upgrade</a>
							<% end %>
						</td>
					</tr>
					<% if @subscription.plan_id != 'free' %>
						<tr id="rowRenewsOn" class="subscription_row">
							<th> Subscription Renews On:</th>
							<td id="nextRenewalCell">
								<%= "--" if @subscription.plan_id == 'free' %>
								<%= DateTime.parse(Time.at(@customer.subscription.current_period_end).to_s).strftime("%m/%d/%Y") unless @subscription.plan_id == 'free' %>
							</td>
						</tr>
						<% if not @card.nil? %>
							<tr id="rowCCInfo" class="subscription_row">
								<th>Payment Method:</th>
								<td id="ccCell">
									<%= "--" if @subscription.plan_id == "free" %>
									<%= "#{@card.type} XXXX-XXXX-XXXX-#{@card.last4}" unless @subscription.plan_id == 'free' %>
								</td>
							</tr>
							<tr id="rowCCExpires" class="subscription_row">
								<th> Card Expires On:</th>
								<td>
									<%= "--" if @subscription.plan_id == "free" %>
									<%= "#{@card.exp_month}/#{@card.exp_year}" unless @subscription.plan_id == 'free' %>
								</td>
							</tr>
						<% end %>
					<% end %>
					<tr id="rowCoupon" class="hide">
						<td colspan="1">
							<div id="couponFormContainer" class="hide">
								<h3><b>Subscription</b></h3>
								<form id="couponForm" class="form-horizontal">
									<div class="coupon-errors alert alert-error hide"></div>
									<div class="control-group">
										<label class="control-label">Standard Subscription</label>
											<div class="controls">
												<input type="text" readonly="true" value="<%= number_to_currency(@standardPlan.amount / 100.00) %>" class="span4" />
											</div>
									</div>
									<div class="control-group">
										<label class="control-label">Coupon</label>
										<div class="controls">
											<input id="coupon" type="text" class="span4" />
										</div>
									</div>
									<div class="form-inputs">
										<button type="submit" class="btn btn-hb" id="couponNext">Next</button>
										<a href="#" class="btn" id="cancelCoupon">Cancel</a>
									</div>
								</form>
							</div>
						</td>
					</tr>
					<tr id="rowForm" class="hide">
						<td colspan="2">
							<div id="paymentFormContainer" class="hide span12">
								<div class="span6">
									<h3 id="paymentFormHeader"><b>Payment Information</b></h3>
									<form id="paymentForm" class='form-horizontall'>
										<input id="subscId" type="hidden" value="<%= @subscription.id %>" />
										<input id="binderId" type="hidden" value="<%= @subscription.binder_id %>" />
										<input id="planId" type="hidden" value="<%= @subscription.plan_id %>" />
										<input id="coupon_id" type="hidden" />
										<div class="payment-errors alert alert-error hide"></div>
										
										<div class="control-group">
											<label class="control-label">Card Number</label>
											<div class="controls">
												<input id="cardNum" type="text" maxlength="16" data-stripe="number" class="span4"/>
												<img id="cardTypes" alt="cards" src="/assets/cctypes.jpg" height="32" width="194">	
											</div>
										</div>
										
										<div class="control-group">
											<label class="control-label">Expiration</label>
											<div class="controls">
												<input type="text" maxlength="2" size="2" data-stripe="exp-month" class="span2" placeholder="MM"/>
												<input type="text" maxlength="4" size="4" data-stripe="exp-year" class="span2" placeholder="YYYY"/>
											</div>
										</div>
										
										<div class="control-group">
											<label class="control-label">CVC</label>
											<div class="controls">
												<input type="text" maxlength="4" data-stripe="cvc" class="span2"/>
											</div>
										</div>
										
												
										<% if @subscription.plan_id == 'free' %>  
											<div id="upgradeSubscritionActions" class="form-inputs">
												<button type="submit" id="upgradeButton" href="#" class="btn btn-success">Upgrade</button>
												<a id="cancelUpgradeButton" href="#" class="btn subsc-btn">Cancel</a>
												<p id="upgrade-info">By clicking Upgrade, I allow HomeBinder.com to charge me the total listed per year.</p>
											</div>
										<% end %>
										
										<% if @subscription.plan_id != 'free' %>
											<div id="updatePaymentActions" class="form-inputs">
												<button type="submit" id="updatePaymentButton" href="#" class="btn btn-success subsc-btn">Update</button>
												<a id="cancelUpdateButton" href="#" class="btn subsc-btn">Cancel</a>
												
												<% if @subscription.payment_status == 'failed' %>
													<p class="sub-text">Payment will be attemted with your new card.</p>
												<% end %>
											</div>	
										<% end %>
									</form>
								</div>
								<% if @subscription.plan_id == 'free' %>
								<div class="span6">
									<table id="tableTotals">
									<tr>
										<th>Sub Total:</th>
										<td id="cellSubTotal" class="confirm-payment"></td>
									</tr>
									<tr>
										<th>Discount:</th>
										<td id="cellDiscount" class="confirm-payment"></td>
									</tr>
									<tr>
										<th>Total:</th>
										<td id="cellTotal" class="confirm-payment"></td>
									</tr>
								</table>
								</div>
								<% end %>
							</div>
						</td>
					</tr>
					<% if @subscription.plan_id != 'free' %>
						<tr id="rowSubTotal" class="subscription_row">
							<th>Sub Total:</th>
							<td id="subTotalCell"><%= number_to_currency(@subtotal / 100.00) %></td>	
						</tr>
						<tr id="rowDiscount" class="subscription_row">
							<th>Discount:</th>
							<td id="discountCell"><%= number_to_currency(@discount / 100.00) %></td>
						</tr>
						<tr id="rowTotal" class="subscription_row">
							<th>Total:</th>
							<td id="totalCell"><%= number_to_currency((@subtotal - @discount) / 100.00) %></td>	
						</tr>
					<% end %>
				</table>
				
				<% if @subscription.plan_id != 'free' and @total > 0.0 %>
					<div id="cancelSubscBlock" class="subsc-action">
						<span><a id="cancelSubsc" href="#" class="subsc-btn">Cancel Subscription</a></span>
						<p class="sub-text">Canceling your subscription does not delete your binder. Your subscriptions will revert back to free.</p>
					</div>
					<div id="updateSubscCardBlock" class="subsc-action">
						<a id="updateSubscCard" href="#" class="subsc-btn">Update Payment Method</a>
					</div>
				<% end %>
				<div id="subscBackBlock" class="subsc-action">
					<%= link_to "Back to Binder", binder_path(@subscription.binder_id), :class => 'subsc-btn' %>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="processingRequest" class="modal hide fade">
	<div class="modal-body">
    	<p>Busy, Please Wait...</p>
  	</div>
</div>